### PR TITLE
Upgrade to Angular 12

### PR DESCRIPTION
**Pull request by WynieCronje**
Upgrading to Angular 12 seems to allow the build to complete :)

### CODE REVIEW

**Comment by WynieCronje** [comment]
image

**Comment by goenning** [comment]
Awesome, thanks for that. Just 2 comments:

Is it much work to move to 13? Seems like 12 is already deprecated.

Also, what you think of disabling/removing the view engine compilation as it's also deprecated?

**Comment by WynieCronje** [comment]
I did try a quick update to 13.. It required dependency updates and extra headaches. So I only did up to 12 as a quick fix.

Once I have more time.. I'll see if I can upgrade to latest of everything. With this we can remove view engine. 

What do you think?

**Comment by goenning** [comment]
Sounds good :+1:

**Pull request merged**
